name: Publish

on:
  workflow_dispatch:
    inputs:
      dir:
        description: "Directory of gem to publish"
        required: true
        default: "resource_detectors/deployment"

jobs:
  Publish:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Checkout
        uses: actions/checkout@v2

      - name: CD into gem directory
        run: cd ${{ github.event.inputs.dir }}

      - name: Bundle Install
        run: bundle install

      - name: Bundle Build
        run: gem build *.gemspec

      # - name: Publish gem
      #   run: |

      #     mkdir -p $HOME/.gem
      #     touch $HOME/.gem/credentials
      #     chmod 0600 $HOME/.gem/credentials
      #     printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      #     gem build *.gemspec
      #     gem push *.gem
      #   env:
      #     GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
