name: Rubocop

on:
  pull_request:
    branches: [master]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bundle Install Root
        run: bundle install

      - name: Bundle Install Each Gem
        run: bundle exec rake bundle_install

      - name: Run rubocop
        run: bundle exec rake rubocop
